// Intrinsic Value Portfolio — data file (edit this to update the site).
// All numbers as pulled from the Master File spreadsheet. marginOfSafety/gain/weight are decimals (0.15 = 15%).
window.PORTFOLIO_DATA = {
  "meta": {
    "title": "Intrinsic Value Portfolio",
    "subtitle": "Tracking The Investor's Podcast — Intrinsic Value",
    "podcastUrl": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/",
    "sourceUpdated": "Jul 23, 2026"
  },
  "totals": {
    "totalValue": 1019212.03,
    "updated": "Jul 23, 2026",
    "nominalCash": 52934.62,
    "endValue2025": 1147000.0,
    "perf2025": "+14.37%",
    "ytd2026": -0.1114106103,
    "cashWeight": 0.05193680848
  },
  "holdings": [
    {
      "name": "Alphabet",
      "ticker": "GOOGL",
      "fairValue": 194.68,
      "currentPrice": 342.09,
      "marginOfSafety": -0.4309099944,
      "targetLastUpdated": "Jan 07, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1Jla7rzVqqACJkx6ElJae4bXS4iECFBIO/edit?usp=sharing&ouid=103928094368337364430&rtpof=true&sd=true",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/alphabet-googl-searching-for-quality-w-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/googl",
      "avgPrice": 178.09,
      "shares": 450.0,
      "gain": 0.9208826998,
      "weight": 0.1510387392
    },
    {
      "name": "Airbnb",
      "ticker": "ABNB",
      "fairValue": 146.35,
      "currentPrice": 140.05,
      "marginOfSafety": 0.04498393431,
      "targetLastUpdated": "Jan 30, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1VevsYYE-6X4TH9rN_xfL6qQauRToe-74/edit?usp=sharing&ouid=103928094368337364430&rtpof=true&sd=true",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/airbnb-abnb-a-silicon-valley-gem-w-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/abnb",
      "avgPrice": 125.3,
      "shares": 894.0,
      "gain": 0.1177174781,
      "weight": 0.1228446057
    },
    {
      "name": "Adobe",
      "ticker": "ADBE",
      "fairValue": 492.0,
      "currentPrice": 218.36,
      "marginOfSafety": 1.253159919,
      "targetLastUpdated": "Apr 30, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1JUL0Rpdys3yBGDwANOLQy-dJPSQpxnh0tZ7X6ouiRrE/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/adobe-designing-a-creative-empire-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/adbe",
      "avgPrice": 364.3,
      "shares": 320.0,
      "gain": -0.4006038979,
      "weight": 0.06855806049
    },
    {
      "name": "Reddit",
      "ticker": "RDDT",
      "fairValue": 245.0,
      "currentPrice": 170.38,
      "marginOfSafety": 0.4379622021,
      "targetLastUpdated": "Feb 05, 2026",
      "modelLink": "https://docs.google.com/spreadsheets/d/1FKA2gXPivzX9T53B5N1Acu9_mPXPY4aQ/edit?usp=sharing&ouid=103928094368337364430&rtpof=true&sd=true",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/reddit-rddt-valuing-the-front-page-of-the-internet-w-shawn-omalley-daniel-mahnke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/rddt",
      "avgPrice": 105.09,
      "shares": 370.78,
      "gain": 0.6212770007,
      "weight": 0.06198268323
    },
    {
      "name": "Uber",
      "ticker": "UBER",
      "fairValue": 80.89,
      "currentPrice": 70.33,
      "marginOfSafety": 0.1501492962,
      "targetLastUpdated": "Apr 30, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/124PEEkm_SmVYeTPwsgH_pWYJR4jaLhmwdUaGOuXRSj8/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/uber-cash-burner-to-compounder-w-shawn-omalley-and-daniel-mahnke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/uber",
      "avgPrice": 77.36,
      "shares": 1416.5,
      "gain": -0.09087383661,
      "weight": 0.09774457332
    },
    {
      "name": "Nubank",
      "ticker": "NU",
      "fairValue": 12.65,
      "currentPrice": 14.51,
      "marginOfSafety": -0.1281874569,
      "targetLastUpdated": "May 15, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1TKJgHitcmx1-0U6yVhYhXUwn0IdfzJp-EBoB-Rthxmo/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/nubank-nu-banking-on-latin-america-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/nu",
      "avgPrice": 11.9,
      "shares": 1681.0,
      "gain": 0.2193277311,
      "weight": 0.0239315366
    },
    {
      "name": "Berkshire Hathaway",
      "ticker": "BRK.B",
      "fairValue": 451.61,
      "currentPrice": 489.39,
      "marginOfSafety": -0.07719814463,
      "targetLastUpdated": "Sep 18, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1xrUA82H1TkFwVrB5PmnJ87vqIctGM0GJVoddZ_Isz-E/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/berkshire-hathaway-brk-b-from-buffett-to-abel-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/brk",
      "avgPrice": 490.42,
      "shares": 64.22,
      "gain": -0.00210024061,
      "weight": 0.0308361998
    },
    {
      "name": "Universal Music Group",
      "ticker": "UMGNF",
      "fairValue": 29.0,
      "currentPrice": 20.7,
      "marginOfSafety": 0.4009661836,
      "targetLastUpdated": "Sep 26, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1YQEmsH8vez8eKjaqsDMtH6YbupKTCjNkaJFUCNfmsEc/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/universal-music-group-umg-owning-the-worlds-music-catalog-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/umg",
      "avgPrice": 24.89,
      "shares": 3647.0,
      "gain": -0.1683406991,
      "weight": 0.07406986748
    },
    {
      "name": "Mercado Libre",
      "ticker": "MELI",
      "fairValue": 2288.45,
      "currentPrice": 1799.21,
      "marginOfSafety": 0.2719193424,
      "targetLastUpdated": "Jan 10, 2026",
      "modelLink": "https://docs.google.com/spreadsheets/d/1kVOZI8vvUWIlaTi8V328oHM1_uBBRgyumu7RAGFFZWw/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/mercado-libre-more-than-just-the-amazon-of-latin-america-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/meli",
      "avgPrice": 1916.28,
      "shares": 30.5,
      "gain": -0.06109232471,
      "weight": 0.05384150048
    },
    {
      "name": "Exor NV",
      "ticker": "EXXRF",
      "fairValue": 128.67,
      "currentPrice": 78.9,
      "marginOfSafety": 0.6307984791,
      "targetLastUpdated": "Jul 15, 2026",
      "modelLink": "https://docs.google.com/spreadsheets/d/1mE4nzEqYcbThyTYV8S1kNloS7EuXXLyu7ndhgmPmcPg/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/exor-nv-exo-too-good-to-be-true-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/exo",
      "avgPrice": 85.5,
      "shares": 932.0,
      "gain": -0.07719298246,
      "weight": 0.07214867744
    },
    {
      "name": "Amazon",
      "ticker": "AMZN",
      "fairValue": 225.0,
      "currentPrice": 244.85,
      "marginOfSafety": -0.08107004288,
      "targetLastUpdated": "Jun 04, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1_TLYTT7b0i4mFoOaB3cllPxH12IgNFUfEPFle53adSI/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/amazon-amzn-is-it-prime-time-for-investors-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/amzn",
      "avgPrice": 197.85,
      "shares": 461.5,
      "gain": 0.2375537023,
      "weight": 0.1108682705
    },
    {
      "name": "CoStar",
      "ticker": "CSGP",
      "fairValue": 55.0,
      "currentPrice": 27.69,
      "marginOfSafety": 0.9862766342,
      "targetLastUpdated": "Apr 23, 2026",
      "modelLink": null,
      "podcastLink": null,
      "newsletterLink": null,
      "avgPrice": 37.34,
      "shares": 590.0,
      "gain": -0.2584359936,
      "weight": 0.01602914754
    },
    {
      "name": "Lifco",
      "ticker": "LFABF",
      "fairValue": null,
      "currentPrice": 32.67,
      "marginOfSafety": null,
      "targetLastUpdated": null,
      "modelLink": "https://docs.google.com/spreadsheets/d/1GopS4vHxYo_AWm4CpOvrfGu_m_MO3UVc/edit?gid=141811405#gid=141811405",
      "podcastLink": "https://www.theinvestorspodcast.com/episodes/ab-lifco-b-st-the-serial-acquirer-building-an-unstoppable-compounding-engine-tip/",
      "newsletterLink": null,
      "avgPrice": 28.36,
      "shares": 705.0,
      "gain": 0.1519746121,
      "weight": 0.02259819284
    },
    {
      "name": "Netflix",
      "ticker": "NFLX",
      "fairValue": 100.0,
      "currentPrice": 68.53,
      "marginOfSafety": 0.4592149424,
      "targetLastUpdated": "Feb 01, 2026",
      "modelLink": "https://docs.google.com/spreadsheets/d/1CcfcvD4cbkz9JzvKrQWalAiALQPQzHJVgc1CSxM6vnA/edit?gid=1047631879#gid=1047631879",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/netflix-nflx-the-king-of-streaming-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/nflx",
      "avgPrice": 75.69,
      "shares": 687.0,
      "gain": -0.09459637997,
      "weight": 0.04619265532
    },
    {
      "name": "Wise PLC",
      "ticker": "WSE",
      "fairValue": null,
      "currentPrice": 12.35,
      "marginOfSafety": -1.0,
      "targetLastUpdated": null,
      "modelLink": null,
      "podcastLink": null,
      "newsletterLink": null,
      "avgPrice": 12.95,
      "shares": 1600.0,
      "gain": -0.04633204633,
      "weight": 0.01938752626
    }
  ],
  "coverage": [
    {
      "name": "MSG Sports",
      "ticker": "MSGS",
      "fairValue": 348.36,
      "currentPrice": 397.25,
      "marginOfSafety": -0.1230711139,
      "targetLastUpdated": "Jan 09, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1sIR2iRYt76Bo6zNgpok8rHDuLUGHjgL8/edit?usp=sharing&ouid=103928094368337364430&rtpof=true&sd=true",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/madison-square-garden-sports-msgs-buying-the-knicks-rangers-w-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/msgs"
    },
    {
      "name": "Coupang",
      "ticker": "CPNG",
      "fairValue": 14.33,
      "currentPrice": 15.63,
      "marginOfSafety": -0.08317338452,
      "targetLastUpdated": "Jan 09, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1L0Ag9oA-c_cwrTHBWqcYIi_Mst8PBXKh/edit?usp=sharing&ouid=103928094368337364430&rtpof=true&sd=true",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/coupang-cpng-the-amazon-of-south-korea-w-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/cpng"
    },
    {
      "name": "Deere",
      "ticker": "DE",
      "fairValue": 405.48,
      "currentPrice": 607.33,
      "marginOfSafety": -0.3323563796,
      "targetLastUpdated": "Jan 09, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1y-2eA3i95rEkua0lidVIv9fLtR4ig3ZL/edit?usp=sharing&ouid=103928094368337364430&rtpof=true&sd=true",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/john-deere-de-sowing-the-seeds-of-growth-w-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/de"
    },
    {
      "name": "Vital Farms",
      "ticker": "VITL",
      "fairValue": 58.08,
      "currentPrice": 13.13,
      "marginOfSafety": 3.42345773,
      "targetLastUpdated": "Jan 09, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/12yY_Sb_vwlzw17CiOT_cVnzyl-eLD8K0/edit?usp=sharing&ouid=103928094368337364430&rtpof=true&sd=true",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/vital-farms-vitl-egg-cellent-value-w-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/vitl"
    },
    {
      "name": "Hershey",
      "ticker": "HSY",
      "fairValue": 170.66,
      "currentPrice": 172.33,
      "marginOfSafety": -0.009690709685,
      "targetLastUpdated": "Jan 10, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1ZP31aaPSrid1G2d0WEWln29l61p5JvAj/edit?usp=sharing&ouid=103928094368337364430&rtpof=true&sd=true",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/hershey-hsy-a-deliciously-beaten-down-stock-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/hsy"
    },
    {
      "name": "Nintendo",
      "ticker": "NTDOY",
      "fairValue": 90.88,
      "currentPrice": 7001.0,
      "marginOfSafety": -0.9870189973,
      "targetLastUpdated": "Mar 12, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1vgioL9YTvZayE9oN9gA9pYibjdTvNoBicQ60cDWjCas/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/nintendo-ntdoy-switching-it-up-w-daniel-mahncke-and-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/ntdoy"
    },
    {
      "name": "VeriSign",
      "ticker": "VRSN",
      "fairValue": 229.09,
      "currentPrice": 262.59,
      "marginOfSafety": -0.1275753075,
      "targetLastUpdated": "Jan 09, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1SFctauwuHG4De8TPzlRRVSEQm3as5Deh/edit?usp=sharing&ouid=103928094368337364430&rtpof=true&sd=true",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/verisign-vrsn-the-internets-toll-road-w-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/vrsn"
    },
    {
      "name": "AutoZone",
      "ticker": "AZO",
      "fairValue": 3318.9,
      "currentPrice": null,
      "marginOfSafety": null,
      "targetLastUpdated": "Jan 08, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/18IPz472SvMH6-mgZyru_p8JFJh76ru5m/edit?usp=sharing&ouid=103928094368337364430&rtpof=true&sd=true",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/autozone-azo-under-the-hood-w-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/azo"
    },
    {
      "name": "Shopify",
      "ticker": "SHOP",
      "fairValue": 67.0,
      "currentPrice": 118.42,
      "marginOfSafety": -0.434217193,
      "targetLastUpdated": "May 26, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/17tnieFnR-Spgb3_sabf2OISs6X1MT9epWE-EmvhEr2g/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/shopify-shop-the-battle-for-the-future-of-e-commerce-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/shop"
    },
    {
      "name": "Visa",
      "ticker": "V",
      "fairValue": 357.6,
      "currentPrice": 353.42,
      "marginOfSafety": 0.01182728765,
      "targetLastUpdated": "May 16, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1FFU1kViBYkBuIxoecdIOD4Nfb8w3IEd7F_qiabR_6J0/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/visa-v-is-visa-still-the-card-to-hold-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/v"
    },
    {
      "name": "Mercedes Benz",
      "ticker": "MBG",
      "fairValue": 41.83,
      "currentPrice": 44.81,
      "marginOfSafety": -0.06650301272,
      "targetLastUpdated": "4/31/25",
      "modelLink": "https://docs.google.com/spreadsheets/d/18EhHWBQ21-aBqPkLqzZmARs4wIp3Qaph9YansGoIG18/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/mercedes-benz-mbg-can-benz-reinvent-the-car-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/mbg"
    },
    {
      "name": "Comfort Systems",
      "ticker": "FIX",
      "fairValue": 323.66,
      "currentPrice": 1791.06,
      "marginOfSafety": -0.8192913694,
      "targetLastUpdated": "Apr 15, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1Rl0ViC2CwyCnrTl10vIyGd32934GWnb4gYDmJyQATB8/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/comfort-systems-fix-blue-collar-compounder-w-shawn-omalley-daniel-mahnke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/fix"
    },
    {
      "name": "Moncler",
      "ticker": "MONC",
      "fairValue": 55.93,
      "currentPrice": 47.61,
      "marginOfSafety": 0.1747532031,
      "targetLastUpdated": "Apr 01, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/194LKqwUqTcr4QRI7u7ePaP6DzP2k1z8K5oacYq2-bEQ/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/moncler-monc-zipped-for-success-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/monc"
    },
    {
      "name": "Blue Owl",
      "ticker": "OWL",
      "fairValue": null,
      "currentPrice": 9.16,
      "marginOfSafety": null,
      "targetLastUpdated": "2/30/25",
      "modelLink": null,
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/blue-owl-capital-owl-the-next-blackstone-w-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/owl"
    },
    {
      "name": "Smith & Wesson",
      "ticker": "SWBI",
      "fairValue": 9.0,
      "currentPrice": 14.62,
      "marginOfSafety": -0.3844049248,
      "targetLastUpdated": "Jun 20, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1pAcP0PNUecHbBXPowEedFQ_W6s0uWnU1ba6l9Q9S8PQ/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/smith-wesson-swbi-deep-value-locked-and-loaded-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/swbi"
    },
    {
      "name": "TSMC",
      "ticker": "TSM",
      "fairValue": 251.0,
      "currentPrice": 421.21,
      "marginOfSafety": -0.4040977185,
      "targetLastUpdated": "Jun 20, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/12FP3y9rpL9A5katq_w86j18HAFE3AfWhcsgib--p69k/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/tsmc-tsm-the-most-important-business-in-the-world-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/tsm"
    },
    {
      "name": "LVMH",
      "ticker": "MC",
      "fairValue": 515.0,
      "currentPrice": 460.15,
      "marginOfSafety": 0.1192002608,
      "targetLastUpdated": "Nov 18, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1Pb_RJZaF06KlTtJezW8KeKi3qamQyi7oc-qeHvBB80I/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/lvmh-mc-investing-in-true-luxury-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/lvmh"
    },
    {
      "name": "Estee Lauder",
      "ticker": "EL",
      "fairValue": 66.97,
      "currentPrice": 82.63,
      "marginOfSafety": -0.189519545,
      "targetLastUpdated": "Jul 14, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1UzXFg-BFvYS1k3HW5smVCOgedVoCZZIQ9QMmeNTgiBg/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/estee-lauder-el-michael-burrys-big-bet-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/el"
    },
    {
      "name": "Roku",
      "ticker": "ROKU",
      "fairValue": 69.57,
      "currentPrice": 143.08,
      "marginOfSafety": -0.5137685211,
      "targetLastUpdated": "Aug 04, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1h9yCe7CjDjcaszIwmDnzqrlqSVJsl7hLk5UpBFwNpms/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/roku-forgotten-streaming-giant-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/roku"
    },
    {
      "name": "Trade Desk",
      "ticker": "TTD",
      "fairValue": 61.49,
      "currentPrice": 17.58,
      "marginOfSafety": 2.497724687,
      "targetLastUpdated": "Aug 04, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1YbHIgm-REu-ayJxwc15Z-CaIcaoT78jzhT6f98_LkOQ/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/the-trade-desk-ttd-heir-to-the-programmatic-advertising-throne-w-shawn-omalley-daniel-mahnke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/ttd"
    },
    {
      "name": "Remitly",
      "ticker": "RELY",
      "fairValue": 20.06,
      "currentPrice": 23.11,
      "marginOfSafety": -0.1319774989,
      "targetLastUpdated": "Aug 11, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1FwOb5lUNBT0Wo594asbXE3nYdJ8tOuW_F8yTsBh2R_I/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/future-multibagger-or-stablecoin-casualty-w-daniel-mahncke-shawn-o-malley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/rely"
    },
    {
      "name": "Ferrari",
      "ticker": "RACE",
      "fairValue": 307.51,
      "currentPrice": 371.61,
      "marginOfSafety": -0.172492667,
      "targetLastUpdated": "Aug 28, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/16pzlzT5HNhXRlIQZ7YKpPgB9t-nIKeGAJJ3uIczD8B0/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/ferrari-race-high-speed-compounder-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/race"
    },
    {
      "name": "Match Group",
      "ticker": "MTCH",
      "fairValue": 35.9,
      "currentPrice": 38.03,
      "marginOfSafety": -0.05600841441,
      "targetLastUpdated": "Sep 15, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1kG6NjUPqdLwsi4cuxZgNZHQtrJlj4Bn_DCYpzdJG9Fg/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/match-group-mtch-is-finding-love-a-good-investment-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/mtch"
    },
    {
      "name": "Dell",
      "ticker": "DELL",
      "fairValue": 99.8,
      "currentPrice": 441.8,
      "marginOfSafety": -0.7741059303,
      "targetLastUpdated": "Sep 07, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1jCPVPkdEhGPMXFl3y4LH4GK1_j32SH6j1LhieLejyiQ/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/dell-overlooked-ai-growth-story-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/dell"
    },
    {
      "name": "Manchester United",
      "ticker": "MANU",
      "fairValue": null,
      "currentPrice": 22.3,
      "marginOfSafety": null,
      "targetLastUpdated": null,
      "modelLink": null,
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/manchester-united-manu-valuing-a-football-empire-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/manu"
    },
    {
      "name": "MSCI",
      "ticker": "MSCI",
      "fairValue": 575.19,
      "currentPrice": null,
      "marginOfSafety": null,
      "targetLastUpdated": "Oct 27, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1SGZqzRiJzKu6VUgt9Z-mWLFE3MNZK-AEft_GndzaIwE/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/msci-the-financial-giant-enabling-passive-investing-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/msci"
    },
    {
      "name": "Fair Isaac Corp.",
      "ticker": "FICO",
      "fairValue": 1100.0,
      "currentPrice": 1221.47,
      "marginOfSafety": -0.09944574979,
      "targetLastUpdated": "Oct 22, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1xos_Jd7G0GC6moqOxmNNr9Edn61anLTgOqQDzFXAD3E/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/fair-isaac-corporation-fico-scoring-the-worlds-biggest-credit-scorer-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/fico"
    },
    {
      "name": "Robinhood",
      "ticker": "HOOD",
      "fairValue": 33.94,
      "currentPrice": 104.48,
      "marginOfSafety": -0.6751531394,
      "targetLastUpdated": "Nov 14, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1AuzB1TAR16YwNAUUW57nOT1Jh79h6K0YxvipC74wKoI/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/robinhood-markets-inc-hood-the-worlds-most-innovative-financial-company-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/hood"
    },
    {
      "name": "Salesforce",
      "ticker": "CRM",
      "fairValue": 253.72,
      "currentPrice": 163.0,
      "marginOfSafety": 0.5565644172,
      "targetLastUpdated": "Nov 18, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1NA6V4oof_QSsi7il1SfmQrzLBnrvJ9Y3TRy9qbZQEuo/edit?gid=0#gid=0",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/salesforce-crm-agentforce-or-ai-native-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/crm"
    },
    {
      "name": "Ulta",
      "ticker": "ULTA",
      "fairValue": 424.85,
      "currentPrice": 483.52,
      "marginOfSafety": -0.1213393448,
      "targetLastUpdated": "Jan 06, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1ITqzPnFFMwUWCPYYZEJiEHLV-tlOvEa4/edit?usp=sharing&ouid=103928094368337364430&rtpof=true&sd=true",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/ulta-beauty-a-beautiful-compounder-w-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/ulta"
    },
    {
      "name": "Booking Holdings",
      "ticker": "BKNG",
      "fairValue": 7628.0,
      "currentPrice": 177.86,
      "marginOfSafety": 41.88766446,
      "targetLastUpdated": "Nov 23, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1PIYBvNtX0dHpj0jStiZtyHqO0TVsUCqGZ4dwv8PULHI/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/booking-holdings-bkng-does-booking-yeah-value-yeah-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/bkng"
    },
    {
      "name": "Snapchat",
      "ticker": "SNAP",
      "fairValue": null,
      "currentPrice": 4.47,
      "marginOfSafety": null,
      "targetLastUpdated": null,
      "modelLink": null,
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/snap-inc-snap-why-hasnt-snapchat-become-a-social-media-titan-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/snap"
    },
    {
      "name": "DoorDash",
      "ticker": "DASH",
      "fairValue": 159.44,
      "currentPrice": 177.73,
      "marginOfSafety": -0.1029089068,
      "targetLastUpdated": "Nov 30, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1fVKBSO5tHqHLfb60_2WnkekoJVmjRvIxY2TmBTLinpc/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/doordash-dash-can-it-keep-delivering-returns-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/dash"
    },
    {
      "name": "Churchill Downs",
      "ticker": "CHDN",
      "fairValue": null,
      "currentPrice": 82.14,
      "marginOfSafety": null,
      "targetLastUpdated": null,
      "modelLink": null,
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/churchill-downs-inc-chdn-investing-in-the-greatest-two-minutes-in-sports-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/chdn"
    },
    {
      "name": "Meta",
      "ticker": "META",
      "fairValue": 698.0,
      "currentPrice": 627.17,
      "marginOfSafety": 0.1129358866,
      "targetLastUpdated": "Jan 27, 2026",
      "modelLink": "https://docs.google.com/spreadsheets/d/12OURVkcmrquwr40UYt6Ed_ifrMzqDjzB_U9Ac1noo88/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/meta-is-meta-undervalued-again-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/meta"
    },
    {
      "name": "Nike",
      "ticker": "NKE",
      "fairValue": 68.23,
      "currentPrice": 42.21,
      "marginOfSafety": 0.6164416015,
      "targetLastUpdated": "Apr 30, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1fBRqpSkA2aZ-XwYtedRN3vUyf21o3lobZQ1aGJ_dHLQ/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/nike-nke-just-buy-it-w-daniel-mahncke-and-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/nike-just-buy-it"
    },
    {
      "name": "Constellation Software",
      "ticker": "CSU",
      "fairValue": 2937.0,
      "currentPrice": 2603.13,
      "marginOfSafety": 0.1282571366,
      "targetLastUpdated": null,
      "modelLink": "https://docs.google.com/spreadsheets/d/12uX1EHfQzEVycacR9qnHir71G7yESZkRuyqyG1gv1oo/edit?gid=0#gid=0",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/constellation-software-csu-historic-drawdown-historic-buying-opportunity-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/csu"
    },
    {
      "name": "Figma",
      "ticker": "FIG",
      "fairValue": null,
      "currentPrice": 21.47,
      "marginOfSafety": null,
      "targetLastUpdated": null,
      "modelLink": null,
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/figma-inc-fig-recovering-from-an-80-post-ipo-decline-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/fig"
    },
    {
      "name": "Duolingo",
      "ticker": "DUOL",
      "fairValue": 105.07,
      "currentPrice": 119.51,
      "marginOfSafety": -0.1208267091,
      "targetLastUpdated": null,
      "modelLink": "https://docs.google.com/spreadsheets/d/1zL6R1_jbMCx3b1PmuJxySSU1-WvUjvkfHSWzgNTpBnY/edit?gid=16614285#gid=16614285",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/duolingo-duol-generational-opportunity-or-fad-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/duol"
    },
    {
      "name": "Lyft",
      "ticker": "LYFT",
      "fairValue": 33.83,
      "currentPrice": 14.66,
      "marginOfSafety": 1.307639836,
      "targetLastUpdated": null,
      "modelLink": "https://docs.google.com/spreadsheets/d/1XyzArqDaiQmIIGPaL5NnAQk34zP4pZsaYN5_duZMDZE/edit?gid=1047631879#gid=1047631879",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/lyft-inc-lyft-the-key-to-winning-the-av-wars-w-shawn-omalley-daniel-mahncke/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/lyft"
    },
    {
      "name": "Hermes",
      "ticker": "RMS",
      "fairValue": 1857.0,
      "currentPrice": 1642.0,
      "marginOfSafety": 0.1309378806,
      "targetLastUpdated": null,
      "modelLink": "https://docs.google.com/spreadsheets/d/1SCsm1OyxClAq2ca7tGrsyk2sDVdde3GmYJkcpGz222Y/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/hermes-the-most-prestigious-luxury-brand-in-the-world-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/rms"
    },
    {
      "name": "TransDigm",
      "ticker": "TDG",
      "fairValue": null,
      "currentPrice": 1194.7,
      "marginOfSafety": null,
      "targetLastUpdated": null,
      "modelLink": "https://docs.google.com/spreadsheets/d/1C6hOOIK5owHvf5YfG0v3D0kPdc2--iBN7-tLaIlrGDk/edit?gid=0#gid=0",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/transdigm-tdg-a-conglomerate-of-monopolies-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/tdg"
    },
    {
      "name": "Copart",
      "ticker": "CPRT",
      "fairValue": null,
      "currentPrice": 27.17,
      "marginOfSafety": null,
      "targetLastUpdated": null,
      "modelLink": "https://docs.google.com/spreadsheets/d/1coxjH1vnfiFMjPIL2TSICqrDyKDi7DXXgmz9I6vAnuE/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/copart-cprt-the-100-bagger-junk-yard-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/cprt"
    },
    {
      "name": "Crocs",
      "ticker": "CROX",
      "fairValue": 94.56,
      "currentPrice": null,
      "marginOfSafety": null,
      "targetLastUpdated": "Aug 25, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1FqRfbDMM8_iaIs6-UlDG5VENya65vEPJ0qW7tp1itBo/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/crocs-crox-fashion-icon-or-value-trap-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/crox"
    },
    {
      "name": "Formula One Group",
      "ticker": "FWONA",
      "fairValue": 65.0,
      "currentPrice": 89.27,
      "marginOfSafety": -0.2718718494,
      "targetLastUpdated": "May 07, 2026",
      "modelLink": "https://docs.google.com/spreadsheets/d/1GVxwnnzx1ie716VcK9QFl9hn2tQi4a8T/edit?gid=141811405#gid=141811405",
      "podcastLink": "https://www.theinvestorspodcast.com/episodes/formula-one-group-fwona-the-only-sports-franchise-worth-owning-tip/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/fwona"
    },
    {
      "name": "NVR",
      "ticker": "NVR",
      "fairValue": null,
      "currentPrice": 6349.28,
      "marginOfSafety": null,
      "targetLastUpdated": null,
      "modelLink": "https://docs.google.com/spreadsheets/d/1X_sbHPShnrl05bsNRClEqirWTD9J88h9/edit?rtpof=true",
      "podcastLink": "https://www.theinvestorspodcast.com/episodes/nvr-whats-next-for-one-of-historys-greatest-compounders-tip/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/nvr"
    },
    {
      "name": "Lululemon",
      "ticker": "LULU",
      "fairValue": 230.0,
      "currentPrice": 48.66,
      "marginOfSafety": 3.726674887,
      "targetLastUpdated": "Aug 11, 2025",
      "modelLink": "https://docs.google.com/spreadsheets/d/1RDgHvH9iYI21eNFmO8x_JO_Pd8qdQj1A1ImiinDhtlw/edit?usp=sharing",
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/lululemon-lulu-still-the-king-of-athleisure-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/lulu"
    },
    {
      "name": "Wix",
      "ticker": "WIX",
      "fairValue": null,
      "currentPrice": 53.58,
      "marginOfSafety": null,
      "targetLastUpdated": null,
      "modelLink": null,
      "podcastLink": null,
      "newsletterLink": null
    },
    {
      "name": "Wise PLC",
      "ticker": "WSE",
      "fairValue": null,
      "currentPrice": 40.25,
      "marginOfSafety": null,
      "targetLastUpdated": null,
      "modelLink": null,
      "podcastLink": "https://www.theinvestorspodcast.com/episodes/wise-plc-w-kyle-grieve-and-daniel-mahncke/",
      "newsletterLink": null
    },
    {
      "name": "Chapters Group",
      "ticker": "CHG",
      "fairValue": null,
      "currentPrice": 37.7,
      "marginOfSafety": null,
      "targetLastUpdated": null,
      "modelLink": null,
      "podcastLink": "https://www.theinvestorspodcast.com/intrinsic-value-podcast/chapters-group-100-bagger-in-the-making-w-daniel-mahncke-shawn-omalley/",
      "newsletterLink": "https://intrinsicvalue.beehiiv.com/p/chg"
    },
    {
      "name": "OTC Markets Group",
      "ticker": "OTCM",
      "fairValue": 64.42,
      "currentPrice": 51.45,
      "marginOfSafety": 0.2520894072,
      "targetLastUpdated": "Apr 29, 2026",
      "modelLink": null,
      "podcastLink": null,
      "newsletterLink": null
    },
    {
      "name": "Perimeter Solutions",
      "ticker": "PRM",
      "fairValue": 46.33,
      "currentPrice": 33.53,
      "marginOfSafety": 0.3817476886,
      "targetLastUpdated": "Jul 09, 2026",
      "modelLink": "https://docs.google.com/spreadsheets/d/1vpADnwiw1EuW4m2puAGLEUYUDQuRcfyJ19VvayXbIz4/edit",
      "podcastLink": null,
      "newsletterLink": null
    }
  ],
  "watchRank": [
    {
      "rank": 1,
      "name": "Meta"
    },
    {
      "rank": 2,
      "name": "Constellation Software"
    },
    {
      "rank": 3,
      "name": "Salesforce"
    },
    {
      "rank": 4,
      "name": "Visa"
    },
    {
      "rank": 5,
      "name": "LVMH"
    },
    {
      "rank": 6,
      "name": "Copart"
    },
    {
      "rank": 7,
      "name": "Lulu"
    },
    {
      "rank": 8,
      "name": "Match Group"
    },
    {
      "rank": 9,
      "name": "Remitly"
    },
    {
      "rank": 10,
      "name": "Ulta"
    }
  ]
};
